baseURL: "https://sharwin24.github.io/toha"

languageCode: "en-us"
title: "Sharwin's Portfolio"
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

module:
  hugoVersion:
    min: "0.128.0"
    extended: true
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
  - source: "dist/katex.js"
    target: ../../assets/scripts/features/math/katex.js
  - source: ../../node_modules/flag-icons/flags
    target: static/flags
  - source: ../../node_modules/@fontsource/mulish/files
    target: static/files
  - source: ../../node_modules/katex/dist/fonts
    target: static/fonts

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    duplicateResourceFiles: false
    extensions:
      cjk:
        eastAsianLineBreaks: false
        eastAsianLineBreaksStyle: simple
        enable: false
        escapedSpace: false
      definitionList: true
      extras:
        delete:
          enable: false
        insert:
          enable: false
        mark:
          enable: false
        subscript:
          enable: false
        superscript:
          enable: false
      footnote: true
      linkify: true
      linkifyProtocol: https
      passthrough:
        delimiters:
          block: []
          inline: []
        enable: false
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderHooks:
      image:
        enableDefault: false
      link:
        enableDefault: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false

# Site parameters
params:
  # Background image of the landing page
  background: /images/kavar_background.jpg
  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/sharwin_portrait.jpg
    inverted: /images/sharwin_portrait.jpg
    favicon: /images/sharwin_portrait.jpg

    # GitHub repo of your site
  gitRepo: https://github.com/Sharwin24/sharwin24.github.io
  # Default branch of your Git repo
  gitBranch: main

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5
  
  # Enable and configure blog posts
  features:
    readingTime:
      enable: true
    blog:
      title: "Project Posts"
      enable: true
      showAuthor: true
    analytics:
      enabled: false
      services:
        google:
          id: "G-D5RCC030C7"

    # specify whether you want to show Table of Contents in reading page
    toc:
      enable: true

    copyCodeButton:
      enable: true

    syntaxHighlight:
      enable: true
      services:
        hljs:
          # see: https://highlightjs.readthedocs.io/en/latest/api.html#configure
          noHighlightRe: /^no-highlight$/i
  
    # Enable this to use `embed-pdf` shortcode.
    embedpdf:
      enable: false

    # Enable this to create flowcharts using shortcodes.
    flowchart:
      enable: false
      services:
        # Uncomment for `mermaid` shortcode.
        mermaid:
          # For config options, see: https://mermaid-js.github.io/mermaid/#/Setup?id=configuration
          # theme: dark

    # Enable this to create mathematic expressions using `$$` blocks
    math:
      enable: true
      services:
        katex: true
        # https://katex.org/docs/autorender.html#api for more configurations

    # Enable to use `video-player` shortcode
    videoPlayer:
      enable: false
      services:
        # convert .js-player class into video player via https://plyr.io/
        # Can play HTML5 Video, Audio, Youtube, Vimeo.
        # For more info on setup: https://github.com/sampotts/plyr#quick-setup
        plyr:
          # options doc: https://github.com/sampotts/plyr#options
          # fullscreen: true
